export const beginnerWords: Record<string, string> = {
    "lunch": "점심 식사",
    "wear": "입다, 신다, 쓰다",
    "child": "아이, 어린이",
    "run": "달리다",
    "call": "전화하다; 부르다",
    "bowl": "(우묵한) 그릇",
    "day": "날, 하루",
    "slow": "느린",
    "fun": "재미; 재미 있는",
    "bicycle": "자전거",
    "loud": "(소리가) 큰, 시끄러운",
    "shelf": "선반",
    "soft": "부드러운, 푹신한",
    "clock": "시계",
    "many": "많은",
    "dream": "꿈꾸다; 꿈, 이상",
    "have": "가지다",
    "puppy": "강아지",
    "family": "가족",
    "store": "가게",
    "teach": "가르치다",
    "eat": "먹다",
    "fine": "좋은, 괜찮은",
    "bath": "목욕",
    "like": "좋아하다; ~처럼",
    "old": "오래된; 나이가 든",
    "kitchen": "부엌, 주방",
    "go": "가다",
    "snack": "간식, 과자",
    "cute": "귀여운",
    "sit": "앉다",
    "student": "학생",
    "name": "이름",
    "closet": "옷장",
    "ready": "준비된",
    "say": "말하다",
    "friend": "친구",
    "wood": "나무, 목재",
    "dinner": "저녁 식사",
    "school": "학교",
    "talk": "말하다, 이야기하다",
    "new": "새로운",
    "together": "함께",
    "meal": "식사",
    "home": "집; 집에, 집으로",
    "same": "같은, 비슷한",
    "read": "읽다",
    "week": "주, 일주일",
    "basket": "바구니",
    "meet": "만나다",
    "easy": "쉬운",
    "elephant": "코끼리",
    "do": "하다",
    "late": "늦은; 늦게",
    "fire": "불",
    "salt": "소금",
    "class": "학급, 반; 수업",
    "teacher": "선생님",
    "bread": "빵",
    "look": "보다",
    "sick": "아픈",
    "goat": "염소",
    "notebook": "공책",
    "garden": "정원",
    "back": "뒤의; 뒤로; 뒤",
    "wash": "씻다",
    "bottle": "병",
    "funny": "웃기는, 재미있는",
    "walk": "걷다",
    "rainbow": "무지개",
    "flower": "꽃",
    "camp": "야영하다",
    "body": "몸, 신체",
    "sad": "슬픈",
    "smile": "미소 짓다; 미소",
    "give": "주다",
    "hair": "머리카락, 털",
    "in": "~의 안에; 안으로",
    "use": "사용하다",
    "market": "시장",
    "kite": "연",
    "farm": "농장",
    "catch": "잡다",
    "sea": "바다",
    "full": "가득 찬",
    "different": "다른",
    "morning": "아침, 오전",
    "sleep": "자다",
    "build": "(건물ㆍ도로를) 짓다",
    "button": "단추; 버튼",
    "know": "알다, 이해하다",
    "stair": "계단",
    "art": "미술(품), 예술",
    "make": "만들다",
    "house": "집",
    "only": "유일한, 단 하나의",
    "living room": "거실",
    "ride": "타다; 타기, 탈 것",
    "long": "긴; 오랜",
    "jungle": "밀림, 정글",
    "race": "경주, 경기",
    "brave": "용감한",
    "bedroom": "침실",
    "hand": "손",
    "mountain": "산",
    "buy": "사다",
    "see": "보다",
    "before": "~앞에, ~전에",
    "clean": "깨끗한; 청소하다",
    "uncle": "삼촌, 고모부, 이모부",
    "tell": "말하다",
    "deep": "깊은",
    "excited": "흥분한, 신이 난",
    "find": "찾다",
    "night": "밤",
    "farmer": "농부",
    "bake": "굽다",
    "get": "받다, 얻다",
    "work": "일하다; 일, 작업",
    "dolphin": "돌고래",
    "hot": "뜨거운, 더운",
    "fast": "빠른; 빨리",
    "building": "건물, 건축",
    "trip": "여행",
    "act": "행동하다",
    "fly": "날다",
    "photo": "사진",
    "hole": "구멍",
    "towel": "수건",
    "break": "깨(지다), 부수다",
    "watch": "보다",
    "weather": "날씨",
    "hospital": "병원",
    "after": "~뒤에, ~후에",
    "king": "왕",
    "leaf": "잎",
    "kid": "아이, 어린이",
    "cheese": "치즈",
    "octopus": "문어",
    "people": "사람들",
    "backpack": "배낭",
    "on": "~의 위에",
    "sunflower": "해바라기",
    "hard": "단단한, 굳은; 어려운",
    "giraffe": "기린",
    "animal": "동물",
    "smell": "냄새를 맡다",
    "sugar": "설탕",
    "number": "수, 숫자; 번호",
    "dry": "마른, 건조한",
    "stand": "서다",
    "grow": "자라다; 기르다",
    "aunt": "이모, 고모, 숙모",
    "safe": "안전한",
    "rose": "장미",
    "want": "원하다",
    "camera": "사진기",
    "climb": "오르다, 등반하다",
    "pea": "완두콩",
    "restaurant": "식당",
    "butter": "버터",
    "large": "큰, 많은",
    "rainy": "비가 오는",
    "help": "돕다, 도와주다; 도움",
    "worm": "(기어 다니는) 벌레",
    "study": "공부하다",
    "mouth": "입",
    "quick": "빠른, 신속한",
    "clothes": "옷, 의복",
    "send": "보내다",
    "near": "가까운; ~가까이에",
    "dress": "원피스; 옷을 입다",
    "onion": "양파",
    "taste": "~한 맛이 나다; 맛",
    "fill": "채우다",
    "cook": "요리하다",
    "river": "강, 하천",
    "draw": "그리다",
    "afternoon": "오후",
    "glue": "풀, 접착제",
    "become": "~이 되다, ~해지다",
    "high": "높은; 높이, 위로",
    "short": "짧은, 키가 작은",
    "pond": "연못",
    "show": "보여주다",
    "cut": "자르다",
    "sport": "스포츠, 운동",
    "young": "(나이가) 어린",
    "playground": "놀이터, 운동장",
    "next": "다음의; 다음에",
    "evening": "저녁",
    "helmet": "헬멧",
    "sunny": "화창한",
    "start": "시작하다",
    "hear": "듣다, 들리다",
    "tent": "텐트",
    "butterfly": "나비",
    "map": "지도",
    "elbow": "팔꿈치",
    "sell": "팔다",
    "face": "얼굴",
    "swim": "수영하다",
    "season": "계절",
    "cloudy": "흐린, 구름이 낀",
    "drink": "마시다",
    "learn": "배우다",
    "strong": "강한, 힘이 센",
    "lady": "여성, 숙녀",
    "close": "닫다; 가까운",
    "put": "놓다, 두다",
    "story": "이야기, 소설",
    "push": "밀다",
    "think": "생각하다",
    "orange": "오렌지",
    "under": "~ 아래에",
    "bakery": "빵집, 제과점",
    "sorry": "미안한",
    "road": "도로, 길",
    "first": "처음의; 우선",
    "tall": "키가 큰",
    "out": "밖으로, 밖에",
    "time": "시간",
    "end": "끝나다",
    "circle": "동그라미, 원",
    "thank": "고마워하다",
    "letter": "편지",
    "from": "~부터, ~에서",
    "scary": "무서운, 두려운",
    "trumpet": "트럼펫",
    "yummy": "맛있는",
    "open": "열려 있는; 열다",
    "sky": "하늘",
    "tower": "탑",
    "fall": "떨어지다; 가을",
    "bridge": "다리",
    "visit": "방문하다",
    "spider": "거미",
    "listen": "듣다",
    "vegetable": "채소",
    "queen": "여왕, 왕비",
    "window": "창문",
    "train": "기차, 열차",
    "fix": "고치다; 고정시키다",
    "every": "모든; 매, 마다",
    "hippo": "하마",
    "tooth": "이, 치아",
    "shout": "외치다",
    "beautiful": "아름다운",
    "strawberry": "딸기",
    "take": "가지고 가다",
    "pan": "납작한 냄비",
    "alone": "혼자인; 혼자, 홀로",
    "winter": "겨울",
    "write": "(글을) 쓰다",
    "pilot": "비행 조종사",
    "live": "살다",
    "light": "가벼운; 빛",
    "feel": "(기분ㆍ감정이) 들다",
    "warm": "따뜻한",
    "sandwich": "샌드위치",
    "life": "생명; 삶, 생활",
    "barn": "헛간",
    "hit": "때리다, 치다",
    "hungry": "배고픈",
    "soccer": "축구",
    "weak": "약한",
    "bubble": "거품, 비눗방울",
    "shake": "흔들(리)다",
    "mop": "대걸레",
    "sure": "확신하는",
    "wet": "젖은",
    "enjoy": "즐기다",
    "water": "물; 물을 주다",
    "summer": "여름",
    "into": "~ 안으로, ~ 안에",
    "dinosaur": "공룡",
    "top": "맨 위; 맨 위의",
    "month": "달, 월",
    "quiet": "조용한",
    "claw": "(동물의) 발톱",
    "heavy": "무거운",
    "color": "색깔",
    "love": "사랑하다",
    "stone": "돌",
    "low": "낮은; 적은",
    "ocean": "바다, 해양",
    "paw": "(동물의) 발",
    "snowy": "눈이 오는",
    "baker": "제빵사",
    "gas": "기체, 가스",
    "wait": "기다리다",
    "again": "다시, 한 번 더",
    "spring": "봄",
    "stop": "멈추다, 그만하다",
    "paint": "페인트칠하다",
    "chick": "병아리",
    "park": "공원",
    "mix": "섞다, 혼합하다",
    "cookie": "쿠키",
    "scarf": "스카프, 목도리",
    "shoe": "신발",
    "umbrella": "우산",
    "lazy": "게으른",
    "inside": "안, 내부 안으로,안에",
    "police": "경찰",
    "wide": "(폭이) 넓은",
    "hose": "호스",
    "weekend": "주말",
    "foot": "발",
    "drive": "운전하다",
    "bank": "은행",
    "wake": "(잠에서) 깨다, 깨우다",
    "blow": "불다",
    "tennis": "테니스",
    "speak": "말하다",
    "crab": "게",
    "drawing": "그림",
    "fry": "(기름에) 튀기다",
    "cousin": "사촌",
    "man": "남자",
    "fan": "선풍기; 팬",
    "year": "해, 연(年); 나이",
    "soup": "수프",
    "nut": "견과",
    "idea": "생각",
    "outside": "바깥(쪽); 밖에",
    "forest": "숲",
    "chef": "요리사",
    "guitar": "기타",
    "shine": "빛나다",
    "ask": "묻다, 질문하다",
    "touch": "만지다",
    "shape": "모양, 형태",
    "sing": "노래하다",
    "dark": "어두운",
    "everyday": "매일의, 일상의",
    "mixture": "혼합, 혼합물",
    "picture": "그림, 사진",
    "dirty": "더러운",
    "broom": "빗자루",
    "noon": "정오, 낮 12시",
    "slide": "미끄러지다",
    "windy": "바람이 부는",
    "hop": "(깡충) 뛰다",
    "deer": "사슴",
    "sink": "가라앉다, 빠지다",
    "present": "선물",
    "round": "둥근, 원형의",
    "pull": "끌다, 당기다",
    "smart": "똑똑한, 영리한",
    "well": "잘, 훌륭하게",
    "cold": "추운, 차가운; 감기",
    "money": "돈",
    "test": "시험, 검사",
    "pianist": "피아노 연주가",
    "bring": "가져오다",
    "ruler": "자",
    "bean": "콩",
    "win": "이기다, 우승하다",
    "front": "앞, 정면; 앞쪽의",
    "question": "질문",
    "turtle": "거북이",
    "drop": "떨어뜨리다",
    "homework": "숙제, 과제",
    "crayon": "크레용",
    "town": "마을, 동네",
    "over": "~의 위에, ~너머로",
    "pipe": "관, 파이프",
    "enter": "들어가다, 들어오다",
    "music": "음악",
    "meat": "고기",
    "birthday": "생일",
    "street": "길, 거리",
    "colorful": "알록달록한",
    "much": "(양이) 많은; 많이",
    "hip": "엉덩이",
    "news": "뉴스, 소식",
    "dig": "파다",
    "plant": "식물; 심다",
    "feeling": "느낌, 감정",
    "answer": "대답하다; 대답",
    "wing": "날개",
    "bright": "밝은, 빛나는",
    "cafe": "카페",
    "heavily": "많이, 몹시, 심하게",
    "pour": "붓다, 따르다",
    "wink": "윙크하다",
    "keep": "두다; 유지하다",
    "here": "여기에(서), 이곳으로",
    "goose": "거위",
    "beach": "해변",
    "paper": "종이",
    "fat": "살찐, 뚱뚱한",
    "team": "(경기 등의) 팀, 조",
    "sunglasses": "선글라스",
    "singer": "가수",
    "sweater": "스웨터",
    "violin": "바이올린",
    "hold": "들다, 잡다",
    "lose": "잃다; 지다",
    "fool": "어리석은 사람, 바보",
    "slice": "조각; (얇게) 썰다",
    "change": "변화시키다, 변하다",
    "everybody": "모든 사람",
    "doctor": "의사",
    "moon": "달",
    "dance": "춤추다",
    "movie": "영화",
    "bookshelf": "책장, 책꽂이",
    "angry": "화난",
    "oil": "기름",
    "person": "사람, 개인",
    "arrive": "도착하다",
    "place": "장소; 두다",
    "classroom": "교실",
    "whale": "고래",
    "difficult": "어려운, 힘든",
    "hurt": "다치게 하다; 아프다",
    "garlic": "마늘",
    "kind": "친절한, 착한",
    "fresh": "신선한",
    "join": "가입하다, 함께 하다",
    "add": "더하다, 추가하다",
    "salty": "(맛이) 짠",
    "lake": "호수",
    "early": "일찍; 이른",
    "floor": "바닥; 층",
    "board": "판자, 널빤지; 타다",
    "move": "움직이다",
    "salad": "샐러드",
    "shoulder": "어깨",
    "vase": "꽃병",
    "busy": "바쁜",
    "sandal": "샌들 한 짝",
    "breakfast": "아침 식사",
    "nurse": "간호사",
    "glove": "장갑 한 쪽",
    "pick": "고르다; 꺾다, 따다",
    "math": "수학",
    "there": "저기에(서), 그곳으로",
    "tonight": "오늘 밤",
    "hate": "싫어하다",
    "word": "단어, 말",
    "land": "땅, 육지; 착륙하다",
    "woman": "여성",
    "trash": "쓰레기",
    "museum": "박물관",
    "penguin": "펭귄",
    "leave": "떠나다; 남기다",
    "boil": "끓다, 끓이다",
    "sweet": "달콤한",
    "plate": "접시",
    "library": "도서관",
    "fruit": "과일",
    "share": "함께 쓰다, 공유하다",
    "behind": "~ 뒤에",
    "choose": "고르다, 선택하다",
    "star": "별",
    "album": "앨범",
    "blanket": "담요",
    "seed": "씨앗",
    "scissors": "가위",
    "messy": "지저분한, 엉망인",
    "worry": "걱정하다",
    "mug": "머그컵",
    "laugh": "(소리 내어) 웃다",
    "clay": "점토, 찰흙",
    "pay": "지불하다",
    "favorite": "가장 좋아하는",
    "line": "선, 줄",
    "space": "공간; 우주",
    "jump": "뛰다, 뛰어오르다",
    "everyone": "모든 사람, 모두",
    "habit": "습관, 버릇",
    "job": "일, 직업",
    "fishbowl": "어항",
    "last": "마지막의; 지난",
    "tongue": "혀",
    "lizard": "도마뱀",
    "fight": "싸우다; 싸움",
    "wall": "벽, 담",
    "invite": "초대하다",
    "coin": "동전",
    "winner": "우승자",
    "honey": "꿀",
    "roof": "지붕",
    "cheer": "응원하다, 환호하다",
    "classmate": "반 친구",
    "order": "순서; 주문하다",
    "glass": "유리, 유리잔",
    "really": "실제로; 아주, 정말",
    "skin": "피부",
    "throw": "던지다",
    "storm": "폭풍",
    "bite": "(이로) 물다, 물어뜯다",
    "sour": "신맛이 나는",
    "bookstore": "서점",
    "quiz": "퀴즈, 시험",
    "telephone": "전화, 전화기",
    "key": "열쇠",
    "pretty": "예쁜",
    "free": "자유로운; 무료의",
    "candle": "초, 양초",
    "thin": "얇은; 마른",
    "snail": "달팽이",
    "sound": "소리",
    "rich": "부유한, 부자인",
    "scream": "비명을 지르다",
    "dragon": "(전설에 나오는 동물) 용",
    "begin": "시작하다",
    "hug": "포옹하다",
    "side": "측면, 면",
    "gray": "회색의",
    "interested": "관심 있는, 흥미 있는",
    "across": "가로질러, 건너편에",
    "happily": "행복하게",
    "bead": "구슬",
    "lie": "거짓말하다; 눕다",
    "mask": "가면",
    "restroom": "화장실",
    "carry": "나르다, 싣다",
    "postcard": "엽서",
    "tired": "피곤한, 지친",
    "player": "선수",
    "club": "클럽, 동아리",
    "wonderful": "멋진, 훌륭한",
    "noisy": "시끄러운, 떠들썩한",
    "kick": "(발로) 차다",
    "hunt": "사냥하다",
    "head": "머리; 가다, 향하다",
    "wolf": "늑대",
    "hundred": "100, 백",
    "cross": "건너다, 가로지르다",
    "television": "텔레비전",
    "painting": "그림",
    "block": "구역; 막다, 방해하다",
    "corner": "모퉁이",
    "seat": "자리, 좌석",
    "right": "맞는; 오른쪽의",
    "stay": "지내다, 머무르다",
    "cave": "동굴",
    "thing": "물건, 것",
    "mirror": "거울",
    "hill": "언덕",
    "scared": "겁먹은, 무서워하는",
    "jacket": "외투, 재킷",
    "tear": "눈물",
    "please": "제발; 기쁘게 하다",
    "bark": "(개가) 짖다",
    "step": "단계; 걸음",
    "ring": "(소리가) 울리다",
    "hurry": "서두르다",
    "firefighter": "소방관",
    "easily": "쉽게",
    "ankle": "발목",
    "hive": "벌집",
    "sharp": "날카로운, 뾰족한",
    "brush": "붓, 빗; 빗질하다",
    "eagle": "독수리",
    "puzzle": "퍼즐, 수수께끼",
    "try": "노력하다, 시도하다",
    "ladybug": "무당벌레",
    "count": "세다, 계산하다",
    "poor": "가난한; 불쌍한",
    "all": "모든, 전체의; 모두",
    "left": "왼쪽의",
    "die": "죽다",
    "mud": "진흙",
    "turn": "돌다; 차례, 순서",
    "narrow": "좁은",
    "lucky": "운이 좋은, 행운의",
    "wild": "야생의",
    "save": "구하다; 모으다",
    "tail": "꼬리",
    "driver": "운전자",
    "grass": "풀, 잔디",
    "bored": "지루한, 싫증난",
    "rice": "쌀, 밥",
    "cheek": "뺨, 볼",
    "computer": "컴퓨터",
    "robot": "로봇",
    "purple": "자줏빛의",
    "magic": "마술, 마법",
    "follow": "따라가다; 따르다",
    "climber": "등반가",
    "quickly": "빨리, 빠르게",
    "flag": "국기, 깃발",
    "sleepy": "졸리는",
    "plan": "계획; 계획하다",
    "erase": "지우다",
    "ink": "잉크",
    "pack": "싸다, 포장하다",
    "tin": "양철로 만든",
    "need": "~를 필요로 하다",
    "miss": "그리워하다; 놓치다",
    "tasty": "맛있는",
    "watermelon": "수박",
    "dirt": "흙, 토양",
    "crocodile": "악어",
    "shiny": "빛나는",
    "cane": "지팡이"
  }
  
  export const intermediateWords: Record<string, string> = {
    "feed": "먹이다",
    "lesson": "수업, 교훈",
    "monster": "괴물",
    "helpful": "도움이 되는, 유익한",
    "nature": "자연",
    "ferry": "여객선, 배",
    "asleep": "잠든, 자고 있는",
    "parent": "(-s) 부모, 어버이",
    "half": "절반, 2분의 1",
    "person": "사람, 개인",
    "about": "~에 대해, ~에 대한, adv. 대략, 약",
    "habit": "습관, 버릇",
    "travel": "여행하다",
    "hide": "숨기다, 숨다",
    "piece": "조각",
    "air": "공기",
    "giant": "거대한",
    "chase": "쫓다",
    "welcome": "환영하다",
    "beautiful": "아름다운",
    "address": "주소",
    "member": "회원, 구성원",
    "both": "둘 다의, 양쪽의, pron. 둘 다, 양쪽",
    "special": "특별한",
    "lovely": "사랑스러운",
    "parrot": "앵무새",
    "footprint": "발자국",
    "shell": "껍데기, 껍질",
    "daily": "매일의, 일상의",
    "nest": "둥지",
    "gift": "선물",
    "lick": "핥다",
    "exercise": "운동하다, 연습하다",
    "far": "멀리, adj. 먼",
    "bloom": "꽃이 피다",
    "island": "섬",
    "world": "세계",
    "mad": "화난",
    "worry": "걱정하다",
    "ask": "묻다, 질문하다, 부탁하다, 요청하다",
    "blood": "피, 혈액",
    "insect": "곤충",
    "dentist": "치과 의사",
    "strange": "이상한, 낯선",
    "note": "메모",
    "until": "~까지, conj. ~할 때까지",
    "muddy": "진흙투성이인",
    "stick": "막대기, 나뭇가지, v. 붙이다",
    "captain": "선장, 기장",
    "each": "각자의, 각각의, pron. 각자, 각각",
    "chore": "허드렛일",
    "bathtub": "욕조",
    "spray": "뿌리다, n. 분무기, 스프레이",
    "action": "행위, 동작",
    "pillow": "베개",
    "shy": "수줍어하는, 부끄럼타는",
    "wrap": "싸다, 포장하다",
    "homework": "숙제, 과제",
    "age": "나이",
    "bored": "지루해 하는",
    "curve": "굽다, 곡선을 이루다",
    "mole": "두더지",
    "fur": "(동물의) 털",
    "village": "마을",
    "hour": "시간",
    "hold": "들다, 잡다",
    "early": "일찍, 빨리, adj. 이른, 빠른",
    "stage": "무대",
    "terrible": "끔찍한, 무서운",
    "hiccup": "딸꾹질",
    "kill": "죽이다",
    "pair": "한 쌍, 켤레",
    "peanut": "땅콩",
    "everywhere": "모든 곳에, 어디든지",
    "more": "더, 더 많은, adv. 더, 더 많이",
    "nickname": "별명",
    "through": "~을 지나서, 통(과)하여",
    "bounce": "튀(기)다, 깡충깡충 뛰다",
    "tomorrow": "내일",
    "rise": "오르다, 올라가다, (해·달이) 뜨다",
    "sketch": "밑그림을 그리다",
    "jeans": "(데님천으로 된) 바지",
    "safe": "안전한",
    "model": "모형, 모델",
    "son": "아들",
    "pay": "(돈을) 지불하다",
    "fill": "채우다",
    "focus": "집중하다",
    "artist": "예술가",
    "cheap": "값싼",
    "tour": "여행, 관광",
    "wrong": "틀린, 잘못된, 나쁜",
    "luck": "행운, 운",
    "bucket": "양동이",
    "branch": "나뭇가지",
    "some": "일부, 약간, adj. 약간의",
    "snore": "코를 골다",
    "rectangle": "직사각형",
    "cucumber": "오이",
    "yard": "뜰, 마당",
    "everything": "모든 것",
    "perfect": "완벽한",
    "plum": "자두",
    "curly": "곱슬곱슬한",
    "soda": "탄산음료",
    "save": "(위험으로부터) 구하다, (돈을) 저축하다",
    "press": "누르다",
    "finally": "마침내, 마지막으로",
    "tiny": "아주 작은",
    "husband": "남편",
    "role": "역할, 임무, (배우의) 배역",
    "health": "건강",
    "ripe": "(과일·곡물이) 익은",
    "area": "지역, 구역",
    "flour": "밀가루",
    "nervous": "긴장한, 불안한",
    "practice": "연습하다, n. 연습",
    "cloth": "천, 옷감",
    "set": "놓다, 두다",
    "enter": "들어가다",
    "contest": "대회",
    "ribbon": "(매듭·장식용) 끈",
    "waist": "허리",
    "true": "진짜의, 진실된",
    "squirrel": "다람쥐",
    "fever": "열",
    "choose": "선택하다, 고르다",
    "earth": "지구",
    "chocolate": "초콜릿",
    "actor": "배우",
    "simple": "간단한, 단순한",
    "later": "나중에, 후에",
    "mail": "우편물, v. (우편으로) 보내다, 부치다",
    "part": "부분, 일부",
    "ginger": "생강",
    "guess": "추측하다",
    "yawn": "하품하다",
    "bump": "부딪히다, 충돌하다",
    "scare": "무섭게 하다, 겁주다",
    "honk": "빵빵거리다",
    "vet": "수의사 (=veterinarian)",
    "toothache": "치통",
    "favorite": "가장 좋아하는",
    "expensive": "비싼",
    "burp": "트림하다",
    "useful": "유용한, 쓸모 있는",
    "mean": "의미하다",
    "beef": "쇠고기",
    "proud": "자랑스러운",
    "straw": "빨대",
    "swimsuit": "수영복",
    "goal": "목표, 목적",
    "own": "자기 자신의, v. 가지다, 소유하다",
    "slice": "(얇게 썬) 조각, v. 얇게 썰다",
    "prince": "왕자",
    "waste": "낭비하다",
    "usually": "보통, 대개",
    "power": "힘",
    "lie": "눕다, 거짓말하다",
    "above": "~보다 위에",
    "spot": "점, 얼룩",
    "marble": "구슬",
    "stay": "머무르다, 남다",
    "starfish": "불가사리",
    "dear": "사랑하는, 친애하는",
    "hang": "걸다, 매달다",
    "princess": "공주",
    "colorfully": "알록달록하게",
    "mind": "마음, 정신",
    "garbage": "쓰레기",
    "away": "떨어져, 멀리",
    "reply": "대답하다",
    "moment": "(특정) 순간, 시점, 잠깐, 잠시",
    "straight": "곧은, 일직선의, adv. 일직선으로, 곧장",
    "silk": "비단, 실크",
    "center": "중심, 한가운데",
    "remember": "기억하다",
    "rub": "비비다, 문지르다",
    "all": "모든, pron. 모두",
    "skateboard": "스케이트보드",
    "lucky": "행운의, 운이 좋은",
    "price": "값, 가격",
    "score": "득점, 점수",
    "jellyfish": "해파리",
    "shoot": "(총 등을) 쏘다",
    "ocean": "대양, 바다",
    "empty": "비어 있는",
    "yell": "소리 지르다, 외치다",
    "grab": "꽉 잡다, 움켜쥐다",
    "pumpkin": "호박",
    "heart": "심장, 마음",
    "visitor": "방문객, 손님",
    "voice": "목소리",
    "pass": "지나가다, 통과하다, 합격하다",
    "tool": "도구, 연장",
    "pattern": "무늬, 모양",
    "wig": "가발",
    "middle": "가운데, 중간",
    "meeting": "회의, 모임",
    "mold": "틀, v. 만들다",
    "bin": "(뚜껑이 있는) 용기, 통",
    "machine": "기계",
    "diary": "일기",
    "wish": "바라다, 원하다",
    "thumb": "엄지손가락",
    "chew": "씹다",
    "cage": "우리, 새장",
    "between": "~의 사이에",
    "hobby": "취미",
    "scream": "비명을 지르다",
    "daughter": "딸",
    "huge": "거대한, 매우 큰",
    "need": "~을 필요로 하다",
    "past": "과거의, 지난, n. 과거",
    "bone": "뼈",
    "chopstick": "젓가락 한 짝",
    "final": "마지막의, 최후의",
    "pretty": "예쁜, adv. 꽤, 매우",
    "space": "우주, 공간",
    "collect": "모으다, 수집하다",
    "date": "날짜",
    "castle": "(구조물) 성",
    "hammer": "망치",
    "gold": "금, 금색",
    "throat": "목구멍, 목",
    "present": "선물, adj. 현재의",
    "alien": "외계인",
    "cereal": "시리얼",
    "backyard": "뒷마당, 뒤뜰",
    "cough": "기침하다",
    "few": "(수가) 거의 없는",
    "amazing": "놀라운, 멋진",
    "pork": "돼지고기",
    "field": "들판, 밭",
    "awake": "깨어 있는",
    "spend": "(돈을) 쓰다, 소비하다, (시간을) 보내다",
    "dust": "먼지",
    "laugh": "(소리 내며) 웃다",
    "order": "명령하다, 지시하다, 주문하다",
    "return": "돌아오다, 돌아가다",
    "bush": "덤불",
    "create": "창조하다, 만들다",
    "shadow": "그림자",
    "famous": "유명한",
    "ticket": "표, 입장권",
    "rich": "부유한, 부자인",
    "forget": "잊다",
    "knife": "칼",
    "lay": "놓다, 두다, (알을) 낳다",
    "daytime": "낮, 주간",
    "wife": "아내, 부인",
    "gorilla": "고릴라",
    "picnic": "소풍",
    "couch": "긴 의자, 소파",
    "page": "페이지, 쪽",
    "item": "물건",
    "nothing": "아무것도 ~ 아니다, 없다",
    "cost": "값, 비용, v. (값·비용이) 들다, 이다",
    "express": "표현하다, 나타내다",
    "country": "국가, 나라",
    "feather": "깃털",
    "alive": "살아 있는",
    "lamb": "어린 양, 양고기",
    "careful": "조심성 있는, 주의 깊은",
    "tickle": "간지럽히다",
    "expression": "표현",
    "way": "길, 방법, 방식",
    "marry": "~와 결혼하다",
    "delicious": "맛있는",
    "speed": "속도, 속력",
    "cartoon": "만화 (영화)",
    "clear": "분명한, 명확한, 맑은, 투명한",
    "mitten": "(한 쪽의) 손모아 장갑 (= 벙어리 장갑)",
    "fence": "울타리, 담",
    "tea": "차",
    "rock": "바위, 돌",
    "moth": "나방",
    "follow": "따라가다, 따라오다, (규칙·충고를) 따르다",
    "healthy": "건강한",
    "medicine": "약",
    "bell": "종, 벨",
    "crosswalk": "횡단보도",
    "tube": "관, 튜브",
    "future": "미래, 장래",
    "happen": "일어나다, 발생하다",
    "yogurt": "요거트",
    "hairdo": "머리 모양",
    "arrive": "도착하다",
    "cube": "정육면체",
    "dead": "죽은",
    "front": "앞쪽의",
    "excellent": "훌륭한, 뛰어난",
    "alone": "혼자인, adv. 혼자, 홀로",
    "minute": "[시간] 분",
    "serve": "(음식을) 제공하다, 차려 주다",
    "view": "경치, 전망, 의견, 생각",
    "burn": "(불에) 타다, 태우다",
    "necklace": "목걸이",
    "smelly": "악취가 나는",
    "chain": "사슬, 쇠줄",
    "lift": "들어 올리다",
    "gentle": "온화한, 친절한",
    "slipper": "슬리퍼, 실내화 한 쪽",
    "lettuce": "상추",
    "stretch": "늘이다, 펴다, 뻗다",
    "ceiling": "천장",
    "nail": "손톱, 발톱, 못",
    "fix": "고치다, 수리하다, 고정시키다",
    "human": "인간, 사람",
    "mosquito": "모기",
    "oval": "타원형의, 계란형의",
    "decide": "결정하다, 결심하다",
    "heat": "열, 더위, v. 가열하다",
    "chance": "기회",
    "weekend": "주말",
    "thick": "두꺼운, 굵은",
    "envy": "부러워하다",
    "planet": "행성",
    "real": "진짜의, 실제의",
    "city": "도시",
    "carpet": "카펫",
    "drawer": "서랍",
    "borrow": "빌리다",
    "trick": "묘기, 장난",
    "floppy": "헐렁한, 늘어진",
    "magician": "마술사",
    "carefully": "조심스럽게, 주의하여",
    "chest": "가슴, 흉부",
    "gate": "문, 대문",
    "problem": "문제(점)",
    "event": "사건, 일, 행사",
    "growl": "으르렁거리다",
    "list": "목록, 명단",
    "smart": "똑똑한, 영리한",
    "wipe": "(손·헝겊으로) 닦다",
    "less": "더 적은, 덜한, adv. 더 적게, 덜하게",
    "check": "확인하다, 점검하다",
    "sail": "항해하다, (배를 타고) 가다",
    "square": "정사각형",
    "sauce": "소스, 양념",
    "season": "계절",
    "badminton": "배드민턴",
    "group": "무리, 집단",
    "ugly": "못생긴, 추한",
    "cart": "수레, 카트",
    "beat": "(반복해서) 치다, 두드리다, 패배시키다, 이기다",
    "nap": "낮잠",
    "meal": "식사",
    "dot": "(동그란) 점",
    "stamp": "우표",
    "valley": "계곡, 골짜기",
    "skinny": "(몸이) 마른",
    "bottom": "맨 아래, 바닥",
    "freeze": "얼다, 얼리다",
    "munch": "우적우적 먹다",
    "every": "모든, 매~, ~마다",
    "spill": "흘리다, 쏟다",
    "finish": "마치다, 끝나다",
    "comb": "빗다, 빗질하다",
    "sunlight": "햇빛, 햇살",
    "die": "죽다, 사망하다",
    "phone": "전화(기)",
    "plastic": "플라스틱",
    "science": "과학",
    "mailbox": "편지함",
    "better": "더 좋은, 더 나은, adv. 더 좋게, 더 잘",
    "desert": "사막",
    "fight": "싸우다",
    "tip": "(뾰족한) 끝, 정보, 조언",
    "mission": "임무",
    "meaning": "뜻, 의미",
    "knock": "두드리다, 노크하다",
    "dangerous": "위험한",
    "horn": "(소·양 등의) 뿔",
    "flat": "평평한, 납작한",
    "triangle": "삼각형",
    "question": "질문",
    "muscle": "근육",
    "invent": "발명하다",
    "fold": "접다",
    "office": "사무실",
    "pajamas": "잠옷, 파자마",
    "vacation": "방학, 휴가",
    "cozy": "편한, 아늑한",
    "cliff": "절벽",
    "leave": "떠나다, 남기다, 놓고 가다",
    "click": "버튼을 누르다, 찰칵 소리가 나다",
    "washroom": "(호텔·식당의) 화장실",
    "seashell": "조개 껍데기",
    "bumpy": "울퉁불퉁한",
    "net": "그물, 망, (테니스 등의) 네트",
    "hope": "바라다, 희망하다",
    "main": "주요한, 주된",
    "example": "예시, 보기",
    "astronaut": "우주 비행사",
    "near": "~가까이에, ~근처로",
    "hike": "하이킹하다, 걸어서 여행하다",
    "history": "역사",
    "guide": "안내자, 안내서, v. 안내하다",
    "writer": "작가",
    "headache": "두통, 머리 아픔",
    "curious": "호기심이 많은, 궁금한",
    "sailor": "선원, 배에서 일하거나 조종하는 사람",
    "along": "~을 따라(서)",
    "thirsty": "목마른",
    "greet": "환영하다, 맞이하다",
    "dessert": "디저트, 후식",
    "fancy": "화려한, 장식이 많은",
    "elevator": "엘리베이터",
    "reach": "도착하다, 도달하다",
    "south": "남쪽",
    "rope": "밧줄",
    "best": "최고의, 가장 좋은, adv. 가장, 가장 잘",
    "behind": "~의 뒤에",
    "fog": "안개",
    "sweat": "땀, v. 땀을 흘리다",
    "point": "가리키다",
    "buzz": "(벌 등이) 윙윙거리다",
    "surprised": "놀란",
    "care": "돌봄, 보살핌, v. 신경 쓰다, 상관하다",
    "bandage": "붕대, 밴드",
    "musical": "음악의, 음악적인, n. 뮤지컬",
    "pepper": "후추",
    "lonely": "외로운, 쓸쓸한",
    "letter": "편지, 글자, 문자",
    "mane": "(말·사자의) 갈기",
    "enough": "충분한, adv. 충분히",
    "clap": "박수치다",
    "difficult": "어려운",
    "silver": "은, 은색",
    "uniform": "교복, 유니폼",
    "believe": "믿다, 신뢰하다",
    "itchy": "가려운",
    "root": "뿌리",
    "pocket": "주머니",
    "station": "(기차) 역, 정거장",
    "concert": "연주회, 콘서트",
    "steal": "훔치다",
    "exit": "출구",
    "rest": "휴식, 안정",
    "mermaid": "인어",
    "pile": "쌓아 놓은 것, 더미, v. 쌓다",
    "blink": "눈을 깜빡이다",
    "spoonful": "한 숟가락",
    "ahead": "앞으로, 앞에",
    "airport": "공항",
    "during": "~동안",
    "diamond": "다이아몬드",
    "crop": "농작물",
    "hint": "실마리, 힌트",
    "second": "두 번째의, n. [시간] 초",
    "subject": "과목",
    "newspaper": "신문",
    "want": "바라다, 원하다",
    "fairy": "요정",
    "soil": "흙, 토양",
    "giggle": "피식 웃다, 킥킥거리다",
    "connect": "연결하다, 접속하다",
    "sword": "칼, 검",
    "fart": "방귀를 뀌다",
    "spell": "철자를 말하다, 쓰다",
    "curtain": "커튼",
    "rooftop": "옥상",
    "shower": "샤워",
    "toilet": "변기",
    "creamy": "크림 같은",
    "firewood": "장작",
    "level": "수준, 단계",
    "handsome": "잘생긴",
    "sponge": "스펀지",
    "hero": "영웅",
    "stinky": "냄새가 지독한, 악취가 나는",
    "rule": "규칙, 규정",
    "hurt": "다치게 하다, 아프다",
    "north": "북쪽",
    "crawl": "(엎드려) 기다, 기어가다",
    "float": "(물 위에) 뜨다, (공중에) 떠다니다",
    "clerk": "점원, 직원",
    "plan": "계획, v. 계획하다",
    "whisper": "속삭이다, 귓속말을 하다",
    "lock": "(자물쇠로) 잠그다",
    "message": "메시지",
    "crispy": "바삭한",
    "stripe": "줄무늬",
    "crown": "왕관",
    "fantastic": "환상적인, 기막히게 좋은",
    "stir": "젓다, (저어 가며) 섞다",
    "often": "자주, 흔히",
    "fingernail": "손톱",
    "squid": "오징어",
    "chop": "잘게 썰다",
    "joy": "즐거움, 기쁨",
    "honest": "정직한",
    "tired": "피곤한, 지친",
    "addition": "추가, 첨가, 추가된 것, 더하기, 덧셈",
    "understand": "이해하다, 알다",
    "change": "변하다, 변화시키다",
    "swing": "흔들다, 흔들리다, 휘두르다",
    "drill": "드릴, 송곳",
    "scientist": "과학자",
    "ground": "지면, 땅",
    "toothbrush": "칫솔",
    "shovel": "삽",
    "quiet": "조용한",
    "flip": "뒤집(히)다",
    "fan": "팬, 지지자, 선풍기, 부채",
    "rectangular": "직사각형의",
    "join": "가입하다, 함께하다",
    "answer": "대답, 답, v. 대답하다",
    "spaceship": "우주선",
    "tale": "이야기, 소설",
    "rooster": "수탉",
    "poster": "벽보, 포스터",
    "spicy": "매운",
    "tissue": "휴지",
    "solve": "해결하다, 풀다",
    "yesterday": "어제, n. 어제",
    "band": "[음악] 밴드",
    "strike": "치다, 때리다",
    "west": "서쪽",
    "rinse": "헹구다, 씻다",
    "tongue": "혀",
    "pine": "소나무",
    "safari": "사파리 여행",
    "surprise": "놀라게 하다",
    "brim": "(컵의) 위 끝부분",
    "popular": "인기 있는",
    "hunter": "사냥꾼",
    "key": "열쇠, adj. 중요한",
    "tape": "테이프",
    "correct": "옳은, 맞는, v. 고치다, 수정하다",
    "energy": "힘, 기운, 에너지",
    "cupboard": "찬장",
    "size": "크기",
    "flashlight": "손전등",
    "secret": "비밀",
    "experiment": "실험",
    "grain": "곡물",
    "promise": "약속하다",
    "cause": "일으키다, 야기시키다",
    "earthworm": "지렁이",
    "blind": "눈이 먼, 시각 장애의",
    "saw": "톱",
    "tie": "묶다, 매다",
    "ghost": "유령, 귀신",
    "important": "중요한",
    "hockey": "하키",
    "subway": "지하철",
    "hen": "암탉",
    "third": "세 번째의",
    "below": "~아래에, ~이하로",
    "story": "이야기",
    "crash": "충돌하다, 추락하다",
    "alarm": "경보(기), 알람, 자명종",
    "zigzag": "지그재그",
    "shape": "형태, 모양",
    "interest": "관심, 흥미",
    "match": "어울리다",
    "miss": "그리워하다, 놓치다",
    "calm": "침착한, 차분한",
    "east": "동쪽",
    "spread": "펴다, 펼치다, 퍼지다",
    "fingerprint": "지문",
    "zoom": "(빠르게) 가다, 질주하다",
    "stem": "(식물의) 줄기",
    "sale": "판매, 할인 판매",
    "toothpaste": "치약",
    "raise": "올리다, 들다, 키우다, 기르다",
    "dip": "살짝 담그다, 적시다",
    "noise": "소음",
    "dairy": "유제품의",
    "narrow": "(폭이) 좁은",
    "shine": "빛나다, 반짝이다",
    "chameleon": "카멜레온",
    "trouble": "문제, 골칫거리",
    "cover": "씌우다, 덮다",
    "prize": "상",
    "mushroom": "버섯",
    "result": "결과",
    "ago": "~전에, 이전에",
    "exam": "시험",
    "wheel": "바퀴",
    "splash": "(물 등을) 튀기다",
    "mess": "엉망진창, 혼란",
    "silly": "어리석은, 바보 같은",
    "wave": "흔들다, n. 파도, 물결",
    "sigh": "한숨을 내쉬다",
    "alligator": "악어",
    "torch": "횃불",
    "musician": "음악가",
    "award": "상, v. (상 등을) 수여하다, 주다",
    "discover": "발견하다",
    "weight": "무게",
    "tasty": "맛있는",
    "step": "걸음, 단계",
    "angel": "천사",
    "surprisingly": "놀랍게도",
    "clip": "핀, 클립",
    "joke": "농담, 우스갯소리",
    "peel": "껍질을 벗기다"
  }
  